### ISSUE TITLE
Profile Pictures not Cropping Properly

### ISSUE THREAD

**Issue by SolDroid** [RefreshAV/Spark-West-Network#40]
![Screenshot from 2019-04-27 14-23-11](https://user-images.githubusercontent.com/25756248/56852995-6f4ce800-68f8-11e9-89ce-47ae0b908fc8.png)

**Comment by nathfreder** [comment]
🤔

**Comment by nathfreder** [comment]
*The image isn't cropping at all.* A image cropper so the user can pick how they want the image to be cropped. 
* https://foliotek.github.io/Croppie/
* https://github.com/transloadit/uppy
