### ISSUE TITLE
Text Formating

### ISSUE THREAD

**Issue by Emma-628** [RefreshAV/Spark-West-Network#49]

**Comment by nathfreder** [comment]
https://github.com/froala/wysiwyg-editor

**Comment by Jellycream** [comment]
looks good. Vue bindings:
https://github.com/froala/vue-froala-wysiwyg/

**Comment by nathfreder** [comment]
@Jellycream the only problem is what to do with the text once we have it, the editor outputs JSON which we would need to render

**Comment by Jellycream** [comment]
I'm sure that can be figured out

**Comment by nathfreder** [comment]
fixed in c8f9b78904d8a7a430f992b76b06f86e73b66a1a
