### ISSUE TITLE
Fix event gallery

### ISSUE THREAD

**Issue by Jellycream** [RefreshAV/Spark-West-Network#53]
The event gallery hasn't been touched since the first implementation of the site. It needs to be completely rebuilt

**Comment by nathfreder** [comment]
do you mean code wise or just the whole thing in general
also: what do you want it to look like?

**Comment by Jellycream** [comment]
@nathfreder I think it'll be easiest to tear the whole thing down and build it from scratch. Idk what it should look like, I'll mess around with it

**Comment by nathfreder** [comment]
after taking a look at Eventbrite, a layout similar to this might work. 
<img width="1280" alt="Screen Shot 2019-07-31 at 9 55 35 am" src="https://user-images.githubusercontent.com/40307305/62213483-65b0a180-b379-11e9-9c6b-b1f77b12d197.png">
the events are on one side and a map with events near me is on the other
<hr>
an older version of Eventbrite had the events on the right and a filter sidebar on the right
<img width="1146" alt="Screen Shot 2019-07-31 at 10 00 46 am" src="https://user-images.githubusercontent.com/40307305/62213810-2767b200-b37a-11e9-903e-57c7dd978b61.png">
