### ISSUE TITLE
Froala costs a bunch of money

### ISSUE THREAD

**Issue by nathfreder** [RefreshAV/Spark-West-Network#57]
<img width="593" alt="Screen Shot 2019-07-31 at 4 30 07 pm" src="https://user-images.githubusercontent.com/40307305/62242021-af68ae80-b3b0-11e9-81b5-dd093ea1d670.png">

https://www.froala.com/wysiwyg-editor/pricing

https://sparkwest.network/events/NewEvent

**Comment by nathfreder** [comment]
@Jellycream

**Comment by nathfreder** [comment]
We could always just say the the textarea supports Markdown and render it with `marked`. That would be free with no licensing. Here's an example: https://vuejs.org/v2/examples/

**Comment by Jellycream** [comment]
I will find a replacement. I had no clue

**Comment by nathfreder** [comment]
@Jellycream Try https://tiptap.scrumpy.io/. It's open-source and built for Vue. 

It exports content in both JSON and HTML. We could store the HTML in Cloud Firestore then render it with the `v-html` attribute.
